DRIVER_OUTPUT_CONTROL = bytes([0x01])
GATE_DRIVING_VOLTAGE_CONTROL = bytes([0x03])
SOURCE_DRIVING_VOLTAGE_CONTRO = bytes([0x04])

INITIAL_CODE_SETTING_OTP = bytes([0x08])
# ICS = Initial Code Setting
WRITE_REGISTER_FOR_ICS = bytes([0x09])
READ_REGISTER_FOR_ICS = bytes([0x0A])

BOOSTER_SOFT_START_CONTROL = bytes([0x0C])

DEEP_SLEEP_MODE = bytes([0x10])

DATA_ENTRY_MODE = bytes([0x11])

SW_RESET = bytes([0x12])

HV_READY_DETECTION = bytes([0x14])

VCI_DETECTION = bytes([0x15])

TEMP_SENSOR_CONTROL = bytes([0x18])
TEMP_SENSOR_CONTROL_WRITE = bytes([0x1A])
TEMP_SENSOR_CONTROL_READ = bytes([0x1B])
TEMP_SENSOR_CONTROL_EXT = bytes([0x1C])

MASTER_ACTIVATION = bytes([0x20])

DISPLAY_UPDATE_CONTROL = bytes([0x21])
DISPLAY_UPDATE_CONTROL_2 = bytes([0x22])

WRITE_RAM_BW = bytes([0x24])
WRITE_RAM_RED = bytes([0x26])
READ_RAM = bytes([0x27])
READ_RAM_OPTION = bytes([0x41])
SET_RAM_X_STARTEND = bytes([0x44])
SET_RAM_Y_STARTEND = bytes([0x45])
AUTO_WRITE_RED_RAM = bytes([0x46])
AUTO_WRITE_BW_RAM = bytes([0x47])
SET_RAM_X_ADDR_COUNTER = bytes([0x4E])
SET_RAM_Y_ADDR_COUNTER = bytes([0x4F])

VCOM_SENSE = bytes([0x28])
VCOM_SENSE_DURATION = bytes([0x29])
PROGRAM_VCOM_OTP = bytes([0x2A])
WRITE_VCOM_CONTROL = bytes([0x2B])
WRITE_VCOM = bytes([0x2C])
OTP_REG_READ = bytes([0x2D])
USER_ID_READ = bytes([0x2E])
STATUS_BIT_READ = bytes([0x2F])
PROGRAM_WS_OTP = bytes([0x30])
LOAD_WS_OTP = bytes([0x31])

WRITE_LUT_REG = bytes([0x32])

CRC_CALCULATION = bytes([0x34])
CRC_STATUS_READ = bytes([0x35])

PROGRAM_OTP_SELECTION = bytes([0x36])
WRITE_REG_DISPLAY = bytes([0x37])
WRITE_REG_USERID = bytes([0x38])
OTP_PROGRAM_MODE = bytes([0x39])

BORDER_WAVEFORM_CONTROL = bytes([0x3C])
END_OPTION = bytes([0x3F])

NOP = bytes([0x7F])


"""
DATA CONSTANTS
"""
DEEP_SLEEP_MODE_NORMAL = bytes([0x00])
DEEP_SLEEP_MODE_ENTER_DSM1 = bytes([0x01])
DEEP_SLEEP_MODE_ENTER_DSM2 = bytes([0x03])
